using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;

namespace uc_online
{
    public class IniConfig_crossplatform
    {
        private string _iniFilePath;
        private Dictionary<string, Dictionary<string, string>> _configData;
        private PlatformType _currentPlatform;

        public enum PlatformType
        {
            Windows,
            Linux,
            MacOS
        }

        public IniConfig_crossplatform(string iniFilePath = "config.ini")
        {
            _iniFilePath = iniFilePath;
            _configData = new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase);
            
            // Detect current platform
            _currentPlatform = DetectPlatform();
            
            LoadConfig();
        }

        private PlatformType DetectPlatform()
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                return PlatformType.Windows;
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                return PlatformType.Linux;
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                return PlatformType.MacOS;
            else
                throw new NotSupportedException($"Platform {RuntimeInformation.OSDescription} is not supported");
        }

        public void LoadConfig()
        {
            _configData.Clear();

            if (!File.Exists(_iniFilePath))
            {
                CreateDefaultConfig();
                return;
            }

            try
            {
                string[] lines = File.ReadAllLines(_iniFilePath);
                string currentSection = "";

                foreach (string line in lines)
                {
                    string trimmedLine = line.Trim();

                    if (string.IsNullOrWhiteSpace(trimmedLine) || trimmedLine.StartsWith(";") || trimmedLine.StartsWith("#"))
                        continue;

                    if (trimmedLine.StartsWith("[") && trimmedLine.EndsWith("]"))
                    {
                        currentSection = trimmedLine.Substring(1, trimmedLine.Length - 2);
                        if (!_configData.ContainsKey(currentSection))
                        {
                            _configData[currentSection] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                        }
                        continue;
                    }

                    if (!string.IsNullOrEmpty(currentSection))
                    {
                        int equalsPos = trimmedLine.IndexOf('=');
                        if (equalsPos > 0)
                        {
                            string key = trimmedLine.Substring(0, equalsPos).Trim();
                            string value = trimmedLine.Substring(equalsPos + 1).Trim();
                            _configData[currentSection][key] = value;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error loading config: {ex.Message}");
                CreateDefaultConfig();
            }
        }

        private void CreateDefaultConfig()
        {
            var defaultConfig = new StringBuilder();
            defaultConfig.AppendLine("; uc-online Crossplatform Configuration File");
            defaultConfig.AppendLine("; This file is automatically generated on first run");
            defaultConfig.AppendLine();
            
            defaultConfig.AppendLine("[uc-online]");
            defaultConfig.AppendLine("AppID = 480");
            defaultConfig.AppendLine("GameExecutable = ");
            defaultConfig.AppendLine("GameArguments = ");
            defaultConfig.AppendLine("SteamAppIdFile = steam_appid.txt");
            defaultConfig.AppendLine();

            // Platform-specific Steam API path comments
            defaultConfig.AppendLine("; Steam API Library Path Configuration");
            switch (_currentPlatform)
            {
                case PlatformType.Windows:
                    defaultConfig.AppendLine("; Windows examples:");
                    defaultConfig.AppendLine("; SteamApiDLLPath = C:\\Program Files (x86)\\Steam\\steam_api.dll");
                    defaultConfig.AppendLine("; SteamApiDLLPath = C:\\Steam\\steam_api64.dll");
                    break;
                case PlatformType.Linux:
                    defaultConfig.AppendLine("; Linux examples:");
                    defaultConfig.AppendLine("; SteamApiDLLPath = ~/.local/share/Steam/steamapps/common/GameName/");
                    defaultConfig.AppendLine("; SteamApiDLLPath = ~/.steam/steam-sdk/");
                    defaultConfig.AppendLine("; SteamApiDLLPath = /usr/local/share/steam/");
                    break;
                case PlatformType.MacOS:
                    defaultConfig.AppendLine("; macOS examples:");
                    defaultConfig.AppendLine("; SteamApiDLLPath = ~/Library/Application Support/Steam/steamapps/common/GameName/");
                    defaultConfig.AppendLine("; SteamApiDLLPath = ~/Library/Application Support/Steam/");
                    break;
            }
            defaultConfig.AppendLine("SteamApiDLLPath = ");
            defaultConfig.AppendLine();

            defaultConfig.AppendLine("[Platform]");
            defaultConfig.AppendLine($"CurrentPlatform = {_currentPlatform}");
            defaultConfig.AppendLine("AutoDetectSteamPath = true");
            
            // Platform-specific Steam paths
            defaultConfig.AppendLine("; Default Steam installation paths (auto-detected)");
            switch (_currentPlatform)
            {
                case PlatformType.Windows:
                    defaultConfig.AppendLine("DefaultSteamPath = C:\\Program Files (x86)\\Steam");
                    break;
                case PlatformType.Linux:
                    defaultConfig.AppendLine("DefaultSteamPath = ~/.local/share/Steam");
                    break;
                case PlatformType.MacOS:
                    defaultConfig.AppendLine("DefaultSteamPath = ~/Library/Application Support/Steam");
                    break;
            }
            defaultConfig.AppendLine();

            defaultConfig.AppendLine("[Logging]");
            defaultConfig.AppendLine("EnableLogging = true");
            defaultConfig.AppendLine("LogFile = uc_online.log");
            defaultConfig.AppendLine("LogLevel = INFO");
            defaultConfig.AppendLine("LogToConsole = true");

            // Platform-specific game paths
            defaultConfig.AppendLine();
            defaultConfig.AppendLine("[GamePaths]");
            switch (_currentPlatform)
            {
                case PlatformType.Windows:
                    defaultConfig.AppendLine("; Common Windows game locations");
                    defaultConfig.AppendLine("; SteamGamesPath = C:\\Program Files (x86)\\Steam\\steamapps\\common");
                    break;
                case PlatformType.Linux:
                    defaultConfig.AppendLine("; Common Linux game locations");
                    defaultConfig.AppendLine("; SteamGamesPath = ~/.local/share/Steam/steamapps/common");
                    defaultConfig.AppendLine("; GamesPath = ~/.steam/steam/steamapps/common");
                    break;
                case PlatformType.MacOS:
                    defaultConfig.AppendLine("; Common macOS game locations");
                    defaultConfig.AppendLine("; SteamGamesPath = ~/Library/Application Support/Steam/steamapps/common");
                    break;
            }
            defaultConfig.AppendLine("; Add your game paths here (one per line)");
            defaultConfig.AppendLine("; CustomGamePath1 = /path/to/your/game");
            defaultConfig.AppendLine("; CustomGamePath2 = /another/game/path");

            try
            {
                File.WriteAllText(_iniFilePath, defaultConfig.ToString());
                LoadConfig();
                Console.WriteLine($"Created default configuration file: {_iniFilePath}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error creating default config: {ex.Message}");
            }
        }

        public void SaveConfig()
        {
            try
            {
                var configBuilder = new StringBuilder();

                foreach (var section in _configData)
                {
                    configBuilder.AppendLine($"[{section.Key}]");

                    foreach (var kvp in section.Value)
                    {
                        configBuilder.AppendLine($"{kvp.Key} = {kvp.Value}");
                    }

                    configBuilder.AppendLine();
                }

                File.WriteAllText(_iniFilePath, configBuilder.ToString());
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error saving config: {ex.Message}");
            }
        }

        public string GetValue(string section, string key, string defaultValue = "")
        {
            if (_configData.TryGetValue(section, out var sectionData) &&
                sectionData.TryGetValue(key, out var value))
            {
                return value;
            }
            return defaultValue;
        }

        public void SetValue(string section, string key, string value)
        {
            if (!_configData.ContainsKey(section))
            {
                _configData[section] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            }

            _configData[section][key] = value;
        }

        // uc-online specific methods
        public uint GetAppID()
        {
            string appIdStr = GetValue("uc-online", "AppID", "480");
            if (uint.TryParse(appIdStr, out uint appId))
            {
                return appId;
            }
            return 480;
        }

        public void SetAppID(uint appId)
        {
            SetValue("uc-online", "AppID", appId.ToString());
        }

        public string GetGameExecutable()
        {
            return GetValue("uc-online", "GameExecutable", "");
        }

        public void SetGameExecutable(string gameExePath)
        {
            SetValue("uc-online", "GameExecutable", gameExePath);
        }

        public string GetGameArguments()
        {
            return GetValue("uc-online", "GameArguments", "");
        }

        public void SetGameArguments(string arguments)
        {
            SetValue("uc-online", "GameArguments", arguments);
        }

        public string GetSteamApiDllPath()
        {
            return GetValue("uc-online", "SteamApiDLLPath", "");
        }

        public void SetSteamApiDllPath(string dllPath)
        {
            SetValue("uc-online", "SteamApiDLLPath", dllPath);
            SaveConfig();
        }

        // Platform-specific methods
        public PlatformType GetCurrentPlatform()
        {
            return _currentPlatform;
        }

        public string GetDefaultSteamPath()
        {
            return GetValue("Platform", "DefaultSteamPath", "");
        }

        public void SetDefaultSteamPath(string steamPath)
        {
            SetValue("Platform", "DefaultSteamPath", steamPath);
        }

        public bool GetAutoDetectSteamPath()
        {
            string value = GetValue("Platform", "AutoDetectSteamPath", "true");
            return bool.TryParse(value, out bool result) && result;
        }

        public void SetAutoDetectSteamPath(bool autoDetect)
        {
            SetValue("Platform", "AutoDetectSteamPath", autoDetect.ToString());
        }

        // Game path management
        public List<string> GetCustomGamePaths()
        {
            var paths = new List<string>();
            
            // Look for custom game path entries
            if (_configData.TryGetValue("GamePaths", out var gamePathsSection))
            {
                foreach (var kvp in gamePathsSection)
                {
                    if (kvp.Key.StartsWith("CustomGamePath") && !string.IsNullOrWhiteSpace(kvp.Value))
                    {
                        // Expand environment variables and tildes
                        string expandedPath = ExpandPath(kvp.Value);
                        if (Directory.Exists(expandedPath) || File.Exists(expandedPath))
                        {
                            paths.Add(expandedPath);
                        }
                    }
                }
            }

            return paths;
        }

        public void AddCustomGamePath(string path)
        {
            var existingPaths = GetCustomGamePaths();
            
            // Find next available CustomGamePath number
            int nextIndex = 1;
            while (_configData.ContainsKey("GamePaths") && 
                   _configData["GamePaths"].ContainsKey($"CustomGamePath{nextIndex}"))
            {
                nextIndex++;
            }

            SetValue("GamePaths", $"CustomGamePath{nextIndex}", path);
        }

        public void RemoveCustomGamePath(string path)
        {
            if (_configData.TryGetValue("GamePaths", out var gamePathsSection))
            {
                var keysToRemove = new List<string>();
                
                foreach (var kvp in gamePathsSection)
                {
                    if (kvp.Key.StartsWith("CustomGamePath"))
                    {
                        string expandedPath = ExpandPath(kvp.Value);
                        if (expandedPath.Equals(path, StringComparison.OrdinalIgnoreCase))
                        {
                            keysToRemove.Add(kvp.Key);
                        }
                    }
                }

                foreach (var key in keysToRemove)
                {
                    gamePathsSection.Remove(key);
                }
            }
        }

        private string ExpandPath(string path)
        {
            if (string.IsNullOrEmpty(path))
                return path;

            // Expand environment variables
            try
            {
                path = Environment.ExpandEnvironmentVariables(path);
            }
            catch
            {
                // Ignore errors in environment variable expansion
            }

            // Expand tilde for home directory (Unix-style)
            if (path.StartsWith("~"))
            {
                string homeDirectory = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
                path = path.Replace("~", homeDirectory);
            }

            // Normalize path separators
            path = Path.GetFullPath(path);

            return path;
        }

        public string GetLogFile()
        {
            return GetValue("Logging", "LogFile", "uc_online.log");
        }

        public bool IsLoggingEnabled()
        {
            string value = GetValue("Logging", "EnableLogging", "true");
            return bool.TryParse(value, out bool result) && result;
        }

        public string GetLogLevel()
        {
            return GetValue("Logging", "LogLevel", "INFO").ToUpper();
        }

        public bool IsConsoleLoggingEnabled()
        {
            string value = GetValue("Logging", "LogToConsole", "true");
            return bool.TryParse(value, out bool result) && result;
        }
    }
}